// Generated by portfolio-admin/scripts/sync-clients.mjs. Publishable key only.
import seed from "./seed.json";
import { resolveContent, type ContentDocument, type SiteId } from "./content";
export const CMS_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://saywjfktkgfgfrnqybck.supabase.co";
export const CMS_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_ojf0lkPRMK3_L4dYScMCaw_aUa4_9Ro";
export const SITE: SiteId = "website";
export const FALLBACK = resolveContent(seed.shared as unknown as ContentDocument, seed.local as unknown as ContentDocument, SITE);
